### ISSUE TITLE
Can't recieve the image. Pillow version is wrong.

### ISSUE THREAD

**Issue by Cirnokiruna** [sszzz830/Project_Sekai_Stickers_QQBot#1]
Can't recieve the image.
![QQ图片20230826171209](https://github.com/sszzz830/Project_Sekai_Stickers_QQBot/assets/143257290/c5b4914e-8791-4c36-9298-9b7e59df2c17)

**Comment by sszzz830** [comment]
This issue doesn't appear to be caused by a version error with the Pillow/PIL library. Please check if the file _'Go-cqhttp/data/images/2186224870.png'_ exists and is the output image you require. If everything is normal, then Pillow is not the issue. Additionally, try sending the /echo command via private message from the admin QQ account you set to see if the bot responds correctly with 'ECHO'. 
Given the limited information you've provided, it's difficult to pinpoint the root cause and solution all at once. I would appreciate it if you could perform the above tests and let me know the results. You may also provide other error messages, such as complete error screenshots from both the Flask and GoCQHTTP sides, to facilitate problem identification and resolution. Thank you.
